CREATE TABLE IF NOT EXISTS MT_MOB (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  AVL VARCHAR(3) NOT NULL,
  TECH VARCHAR(1000) NOT NULL,
  BANDS_2G VARCHAR(100) NOT NULL,
  BANDS_3G VARCHAR(100) NOT NULL,
  BANDS_4G VARCHAR(100) NOT NULL,
  UNIQUE KEY MMOB_UNQ(NAME)
);

CREATE TABLE IF NOT EXISTS MT_MOB_BOOK_HSTRY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MOB_ID INT NOT NULL,
  BKD_ON DATE,
  BKD_BY VARCHAR(20)
);

ALTER TABLE MT_MOB_BOOK_HSTRY ADD CONSTRAINT MMBH_FKEY FOREIGN KEY(MOB_ID) REFERENCES MT_MOB(ID);